AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Lambda function for translation
Resources:
  imageAnalyzerLambdaTranslation:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: image-analyzer-lambda-translation
      AutoPublishAlias: prod
      Handler: cloud.developing.imageanalyzer.translation.Translation::translate
      Runtime: java8
      CodeUri: ./build/distributions/image-analyzer-lambda-translation.zip
      MemorySize: 512
      Timeout: 30
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/lambda_exec_role
      Layers: 
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:image-analyzer-lambda-layer:3